backend:
  name: git-gateway
  branch: eleventy
publish_mode: editorial_workflow
site_url: 'https://lh-web.netlify.com/'
media_folder: 'media/uploads'
public_folder: 'uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Homepage'
        delete: false
        file: 'src/index.md'
        slug: '{{slug}}'
        create: false
        fields:
          - {
              label: 'Layout',
              name: 'layout',
              widget: 'hidden',
              default: 'base.njk',
            }
          - {
              label: 'SEO Meta Title',
              name: 'metaTitle',
              widget: 'string',
              required: false,
            }
          - {
              label: 'SEO Meta Description',
              name: 'metaDesc',
              widget: 'string',
              required: false,
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Sub Title', name: 'subTitle', widget: 'string' }
          - {
              label: 'Social Image',
              name: 'socialImage',
              widget: 'image',
              required: false,
            }
  - name: 'news'
    label: 'News'
    folder: 'src/news'
    create: true
    preview_path: 'news/{{slug}}'
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'base.njk',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'SEO Meta Title',
          name: 'metaTitle',
          widget: 'string',
          required: false,
        }
      - {
          label: 'SEO Meta Description',
          name: 'metaDesc',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Social Image',
          name: 'socialImage',
          widget: 'image',
          required: false,
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Globals'
    name: 'globals'
    files:
      - label: 'Site Data'
        name: 'site_data'
        delete: false
        file: 'src/_data/site.json'
        fields:
          - { label: 'Site Name', name: 'name', widget: 'string' }
          - { label: 'Site Url', name: 'url', widget: 'string' }
          - {
              label: 'Maximum News Articles Per Page',
              name: 'maxNewsPerPage',
              widget: 'number',
              default: 3,
            }
          - {
              label: 'Favicon path (EG: /media/favicon.png)',
              name: 'faviconPath',
              widget: 'string',
            }
